handle missing HEREDOC endline at start of heredoc
ruby/yarp pull request #1261
Opened 2023-08-15 19:09 UTC by HParker

Found via: https://github.com/BlakeWilliams/backbone_handlebars/blob/master/lib/backbone_handlebars/template.rb#L30

2023-08-15 19:16 UTC, kddnewton requested changes

2023-08-15 19:16 UTC, kddnewton commented on src/util/yp_newline_list.c
> +    if (list->size == 0 || newline_offset > list->offsets[list->size - 1]) {
I think we want to keep around the assertion. It looks like we're probably calling this in a place we shouldn't be.

2023-08-15 19:16 UTC, kddnewton commented on src/yarp.c
> +            if (parser->heredoc_end) {
I don't think we want to handle this here. I think it's probably likely that we're handling the escape somewhere and not flushing the `heredoc_end` as we should be.

Maybe take a look where we are currently handling `\` in `YP_LEX_DEFAULT`? I'd bet we aren't checking for a heredoc.

2023-08-16 16:29 UTC, kddnewton commented on src/yarp.c
> +            if (parser->heredoc_end) {
@HParker if you don't mind removing this section, I think it's good.

2023-08-17 16:20 UTC, HParker commented on .gitattributes
> -**/*.txt text eol=lf
I think this removes all `\r\n` on checkout. Let me know if there is a different configuration I am not understanding.

2023-08-17 16:22 UTC, HParker commented on .gitattributes
> -**/*.txt text eol=lf
Ah, looks like you already did this on main, but better.

2023-08-17 16:28 UTC, closed without merging

2023-08-17 16:43 UTC, HParker commented
Somehow I rebased this branch into oblivion. Re-opened here: https://github.com/ruby/yarp/pull/1278