Match EOF after newline behavior
ruby/yarp pull request #1306
Opened 2023-08-22 17:54 UTC by HParker

in Ripper EOL after whitespace is returned as a on_nl node with the whitespace as the content.

2023-08-22 21:21 UTC, kddnewton commented
@HParker I don't think replicating it in our lexer necessarily buys us anything other than compatibility since we don't need it for the token stream. What do you think of replicating it in `lex_compat` instead?

2023-08-22 21:22 UTC, kddnewton requested changes
Just marking this as "request changes"

2023-08-23 14:02 UTC, HParker commented
@kddnewton how does this look?

I think this is the only case where there is a `on_nl` without a `\n` in it, but maybe you have a better idea how to identify it.

2023-08-23 14:32 UTC, kddnewton commented
@HParker ahh I'm so sorry I misled you. I meant in our lex_compat, not changing ripper's output. I'm saying we should change our function (on the Ruby side) to return this extra token.

2023-08-23 17:22 UTC, kddnewton approved these changes

2023-08-23 17:23 UTC, merged